--------------------------------------------------------
-- 1) CREATION DES TABLES
--------------------------------------------------------
DROP TABLE IF EXISTS rendez_vous;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS utilisateur;
DROP TABLE IF EXISTS travailleurs;

-- Table patient
CREATE TABLE patient
(
    "id_patient"      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "prenom"          VARCHAR(50) NOT NULL,
    "nom"             VARCHAR(50) NOT NULL,
    "telephone"       VARCHAR(20),
    "date_naissance"  DATE,
    "numero_identite" VARCHAR(50) NOT NULL UNIQUE
    -- Modification réalisée : ajout de NOT NULL et UNIQUE pour numero_identite
);

-- Table utilisateur
CREATE TABLE utilisateur
(
    "id_utilisateur" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mot_de_passe"   VARCHAR(255) NOT NULL,
    "email"          VARCHAR(100) NOT NULL UNIQUE,
    "role"           INT          NOT NULL, -- Ajout de la colonne de liaison vers la table role
    "nom"            VARCHAR(50),
    "prenom"         VARCHAR(50),
    "telephone"      VARCHAR(20)  NOT NULL UNIQUE
);

-- Table travailleurs
CREATE TABLE travailleurs
(
    "id_travailleur"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "horaire_regime_travail" VARCHAR(50),
    "couleur"                VARCHAR(9)
);

-- Table rendez_vous
CREATE TABLE rendez_vous
(
    "id_rendez_vous" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date_debut"     TIMESTAMP NOT NULL,
    "date_fin"       TIMESTAMP NOT NULL,
    "description"    TEXT,
    "motif_rdv"      VARCHAR(100),
    "id_patient"     INT       NOT NULL,
    "id_utilisateur" INT       NOT NULL,
    CONSTRAINT fk_rv_patient
        FOREIGN KEY ("id_patient")
            REFERENCES patient ("id_patient"),
    CONSTRAINT fk_rv_utilisateur
        FOREIGN KEY ("id_utilisateur")
            REFERENCES utilisateur ("id_utilisateur")
);
